export const ContentData =[
    {   
        id:'figma',
        title:'Figma',
        subtitle:'Figma is a cloud-based design and prototyping tool that is widely used by UI/UX designers, product teams, and design agencies. It offers a collaborative environment where multiple team members can work simultaneously on the same project, making it ideal for remote collaboration.',
        images:['figma1.jpg','figma2.jpg','figma3.jpg'],
        icon:'figma.svg',
    },
    {
        id:'illustractor',
        title:'Illustractor',
        subtitle:'Figma is a cloud-based design and prototyping tool that is widely used by UI/UX designers, product teams, and design agencies. It offers a collaborative environment where multiple team members can work simultaneously on the same project, making it ideal for remote collaboration.',
        images:['illustractor1.jpg','illustractor2.jpg','illustractor3.jpg'],  
        icon:'illustractor.svg',        
    },
    {
        id:'photoshop',
        title:'Photoshop',
        subtitle:'Photoshop is a cloud-based design and prototyping tool that is widely used by UI/UX designers, product teams, and design agencies. It offers a collaborative environment where multiple team members can work simultaneously on the same project, making it ideal for remote collaboration.',
        images:['photoshop1.jpg','photoshop2.jpg','photoshop3.jpg'],
        icon:'photoshop.svg',            
    },
    {
        id:'javascript',
        title:'Javascript',
        subtitle:'javascript is a cloud-based design and prototyping tool that is widely used by UI/UX designers, product teams, and design agencies. It offers a collaborative environment where multiple team members can work simultaneously on the same project, making it ideal for remote collaboration.',
        images:['javascript1.jpg','javascript2.jpg','javascript3.jpg'],          
        icon:'javascript.svg',  
    },   
    {
        id:'sass',
        title:'SASS',
        subtitle:'SASS is a cloud-based design and prototyping tool that is widely used by UI/UX designers, product teams, and design agencies. It offers a collaborative environment where multiple team members can work simultaneously on the same project, making it ideal for remote collaboration.',
        images:['sass1.jpg','sass2.jpg','sass3.jpg'], 
        icon:'sass.svg',           
    }, 
    {
        id:'html',
        title:'HTML5',
        subtitle:'HTML5 is a cloud-based design and prototyping tool that is widely used by UI/UX designers, product teams, and design agencies. It offers a collaborative environment where multiple team members can work simultaneously on the same project, making it ideal for remote collaboration.',
        images:['html1.jpg','html2.jpg','html3.jpg'],          
        icon:'html.svg',  
    },
    {
        id:'css',
        title:'CSS3',
        subtitle:'CSS3 is a cloud-based design and prototyping tool that is widely used by UI/UX designers, product teams, and design agencies. It offers a collaborative environment where multiple team members can work simultaneously on the same project, making it ideal for remote collaboration.',
        images:['css1.jpg','css2.jpg','css3.jpg'], 
        icon:'css.svg',
    }, 
    {
        id:'wordpress',
        title:'Wordpress',
        subtitle:'Wordpress is a cloud-based design and prototyping tool that is widely used by UI/UX designers, product teams, and design agencies. It offers a collaborative environment where multiple team members can work simultaneously on the same project, making it ideal for remote collaboration.',
        images:['wordpress1.jpg','wordpress2.jpg','wordpress3.jpg'],
        icon:'wordpress.svg',
    }, 
    {
        id:'joomla',
        title:'Joomla',
        subtitle:'Joomla is a cloud-based design and prototyping tool that is widely used by UI/UX designers, product teams, and design agencies. It offers a collaborative environment where multiple team members can work simultaneously on the same project, making it ideal for remote collaboration.',
        images:['joomla1.jpg','joomla2.jpg','joomla3.jpg'],  
        icon:'joomla.svg',
    }, 
    {
        id:'opencart',
        title:'Opencart',
        subtitle:'Opencart is a cloud-based design and prototyping tool that is widely used by UI/UX designers, product teams, and design agencies. It offers a collaborative environment where multiple team members can work simultaneously on the same project, making it ideal for remote collaboration.',
        images:['opencart1.jpg','opencart2.jpg','opencart3.jpg'],
        icon:'opencart.svg',
    }, 
    {
        id:'linkedin',
        title:'LinkedIn',
        subtitle:'LinkedIn is a cloud-based design and prototyping tool that is widely used by UI/UX designers, product teams, and design agencies. It offers a collaborative environment where multiple team members can work simultaneously on the same project, making it ideal for remote collaboration.',
        images:['opencart1.jpg','opencart2.jpg','opencart3.jpg'], 
        icon:'linkedin.svg',
        iframe:true,         
    },  
    {
        id:'youtube',
        title:'Youtube',
        subtitle:'Youtube is a cloud-based design and prototyping tool that is widely used by UI/UX designers, product teams, and design agencies. It offers a collaborative environment where multiple team members can work simultaneously on the same project, making it ideal for remote collaboration.',
        images:['opencart1.jpg','opencart2.jpg','opencart3.jpg'], 
        icon:'youtube.svg',
        iframe:true,
    },
    {
        id:'profile',
        title:null,
        subtitle:'Description',
        layout:'second',
        icon:'folder.svg',
    },
    {
        id:'document',
        title:'document',
        subtitle:'Description',
        icon:'folder.svg',
    },
    {
        id:'gallery',
        title:'gallery',
        subtitle:'Description',
        icon:'folder.svg',
    },
    {
        id:'settings',
        title:'settings',
        subtitle:'Description',
        icon:'folder.svg',
    } 

]